// Для списка специализаций
export const SPECIALISATION_LIST_FETCHING: string = 'SPECIALISATION_LIST_FETCHING';
export const SPECIALISATION_LIST_FETCHED: string = 'SPECIALISATION_LIST_FETCHED';
export const SPECIALISATION_LIST_FETCHED_ERR: string = 'SPECIALISATION_LIST_FETCHED_ERR';

// Для одной специализации
export const SPECIALISATION_ITEM_FETCHING: string = 'SPECIALISATION_ITEM_FETCHING';
export const SPECIALISATION_ITEM_FETCHED: string = 'SPECIALISATION_ITEM_FETCHED';
export const SPECIALISATION_ITEM_FETCHED_ERR: string = 'SPECIALISATION_ITEM_FETCHED_ERR';
