export const SET_MASTERS = 'SET_MASTERS';
export const ADD_MASTER = 'ADD_MASTER';
export const DELETE_MASTER = 'DELETE_MASTER';
export const START_EDIT_MASTER = 'START_EDIT_MASTER';
export const MASTERS_ARE_LOADING = 'MASTERS_ARE_LOADING';
export const MASTERS_HAS_ERRORED = 'MASTERS_HAS_ERRORED';
export const SAVE_UPDATED_MASTER = 'SAVE_UPDATED_MASTER';
