export const PROFILE_IS_LOADING = 'PROFILE_IS_LOADING';
export const PROFILE_HAS_ERRORED = 'PROFILE_HAS_ERRORED';
export const SET_PROFILE = 'SET_PROFILE';
export const SAVE_UPDATED_PROFILE = 'SAVE_UPDATED_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
